### ISSUE TITLE
0.4.3 not published on Docker Hub

### ISSUE THREAD

**Issue by jhead** [OpenRCT2/openrct2-docker#14]
Looks like there's a Dockerfile in the repo but it's not published yet:
https://hub.docker.com/r/openrct2/openrct2-cli/tags

**Comment by wallzero** [comment]
@Gymnasiast mind taking a look?

**Comment by wallzero** [comment]
@IntelOrca when I try using `:latest` or `:0.4.2`, I get the following errors:

```
[#ALPINEC] Object not found.
[TTRFWD01] Object not found.
[TTRFWD02] Object not found.
[TTRFWD03] Object not found.
[TTRFWD04] Object not found.
[TTRFWD06] Object not found.
[TTRFWD07] Object not found.
[TTRFWD08] Object not found.
[ACWW33  ] Object not found.
[ACWWF32 ] Object not found.
Unable to open park: missing objects
```

When I use `:develop`, the server works properly. But since `:develop` is `0.4.3-1`, the current stable clients won't connect with error `Disconnected: Incorrect Software Version (Server is using 0.4.3-1)`.
