### ISSUE TITLE
0.4.4 Dockerfile + image missing

### ISSUE THREAD

**Issue by mvnmgrx** [OpenRCT2/openrct2-docker#15]
Looks like the Dockerfile for version 0.4.4 is missing and it is also not published on Docker Hub:
https://hub.docker.com/r/openrct2/openrct2-cli/tags

Could someone add the newest release to Docker Hub?

**Comment by Gymnasiast** [comment]
Looks like it has been added: https://hub.docker.com/layers/openrct2/openrct2-cli/0.4.4/images/sha256-6eccee56254e83c4db08e647718eddab0b43d8e58ec2a865ac4bea3da537fdc7?context=explore
