### ISSUE TITLE
Attempting to mount a volume causes a filesystem permission error

### ISSUE THREAD

**Issue by mjrossi** [OpenRCT2/openrct2-docker#6]
Hello!

I'm attempting to use this docker container for a dedicated server, but would like to be able to mount the config files locally, which in this repo is shown with the following example command:

`docker run --rm -p 11753:11753 -v /home/me/openrct2-config:/home/openrct2/.config/OpenRCT2 -it openrct2/openrct2-cli host /home/openrct2/.config/OpenRCT2/save/mypark.sv6`

Whenever I try to run this, I get the following error and the container dies

```
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: status: Permission denied [/home/openrct2/.config/OpenRCT2/config.ini]
```

Things I have tried in order to resolve:
1. Get a copy of the files stored in `.config/OpenRCT2` and save them to my local volume before creating the container (thought perhaps there was an issue creating them)
2. Ensuring all permissions to my local files include read/write to the docker daemon user.

Any other ideas on what I could try, or perhaps this is an actual bug?

Thanks!

EDIT: Another note that I forgot to add...I got my copy of the `.config/OpenRCT2` files from this image, but starting it up without the volume mount so it could load (the first example on this repo's readme). I used `docker cp` to copy them locally and one of the things I noticed is the permissions, before I changed them, included a few different users / groups. Curious if the permissions issue is because the container uses an underlying Ubuntu image with all the files being owned by a different group than my local docker daemon is running as?

**Comment by mjrossi** [comment]
It would appear the user that owns the files is `openrct2` - e.g.
```
ls -ahl
> drwxr-xr-x 1 openrct2 openrct2 292 Oct 25 14:25 OpenRCT2
```

Possible that's the mismatch with a local volume, but at this point I'm just thinking out loud a bit

**Comment by IntelOrca** [comment]
Try `-u 0`, the container will then run as root and have full access.

E.g.
```
docker run --rm -u 0 -p 11753:11753 -v /home/me/openrct2-config:/home/openrct2/.config/OpenRCT2 -it openrct2/openrct2-cli host /home/openrct2/.config/OpenRCT2/save/mypark.sv6
```

**Comment by mjrossi** [comment]
Excellent! I'll probably mess with this a bit to see if I can figure out some way not have to run as root, but TIL `-u 0` is a thing and it seems to work just fine.

Appreciate the fast reply - thank you!

**Comment by mbugert** [comment]
To anyone looking for a quick solution: using the `www-data` user works.

```bash
mkdir openrct2-config
chown www-data:www-data openrct2-config
docker run \
  --rm \
  -u www-data:www-data \
  -p 11753:11753 \
  -v ./openrct2-config:/var/www/.config/OpenRCT2 \
  -it openrct2/openrct2-cli host https://bit.do/openrct2-bpb
```
